services:
  - type: web
    name: kinetra-auth-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/AuthService
    dockerfilePath: backend/AuthService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: Jwt__Audience
        sync: false
      - key: Jwt__SecretKey
        sync: false
      - key: Seed__AdminEmail
        sync: false
      - key: Seed__AdminPassword
        sync: false

  - type: web
    name: kinetra-riders-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/RidersService
    dockerfilePath: backend/RidersService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false

  - type: web
    name: kinetra-orders-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/OrdersService
    dockerfilePath: backend/OrdersService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false

  - type: web
    name: kinetra-routes-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/RoutesService
    dockerfilePath: backend/RoutesService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false

  - type: web
    name: kinetra-payments-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/PaymentsService
    dockerfilePath: backend/PaymentsService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false

  - type: web
    name: kinetra-notifications-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/NotificationsService
    dockerfilePath: backend/NotificationsService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false

  - type: web
    name: kinetra-reports-service
    runtime: docker
    plan: starter
    region: oregon
    dockerContext: backend/ReportsService
    dockerfilePath: backend/ReportsService/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
      - key: ConnectionStrings__Default
        sync: false
