version: "3.9"

services:
  auth-service:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
      Jwt__Issuer: ${AUTH_JWT_ISSUER:-}
      Jwt__Audience: ${AUTH_JWT_AUDIENCE:-}
      Jwt__SecretKey: ${AUTH_JWT_SECRET:-}
      Seed__AdminEmail: ${AUTH_ADMIN_EMAIL:-}
      Seed__AdminPassword: ${AUTH_ADMIN_PASSWORD:-}
    networks:
      - kinetra-net

  riders-service:
    build:
      context: ./RidersService
      dockerfile: Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  orders-service:
    build:
      context: ./OrdersService
      dockerfile: Dockerfile
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  routes-service:
    build:
      context: ./RoutesService
      dockerfile: Dockerfile
    ports:
      - "5004:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  payments-service:
    build:
      context: ./PaymentsService
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  notifications-service:
    build:
      context: ./NotificationsService
      dockerfile: Dockerfile
    ports:
      - "5006:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  reports-service:
    build:
      context: ./ReportsService
      dockerfile: Dockerfile
    ports:
      - "5007:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: ${CONNECTION_STRING:-}
    networks:
      - kinetra-net

  gateway:
    image: nginx:1.25-alpine
    depends_on:
      - auth-service
      - riders-service
      - orders-service
      - routes-service
      - payments-service
      - notifications-service
      - reports-service
    ports:
      - "8080:80"
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - kinetra-net

networks:
  kinetra-net:
    driver: bridge
